// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCog2BFE88p1Zo1OML_44DO6HIVEVwh8zc',
    appId: '1:488476540503:web:c27a3af686a41338076d12',
    messagingSenderId: '488476540503',
    projectId: 'andriod-43852',
    authDomain: 'andriod-43852.firebaseapp.com',
    storageBucket: 'andriod-43852.firebasestorage.app',
    measurementId: 'G-YC0TX164WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGChMSAfvrYfEWYatEPA1FTwSrMZpC-RQ',
    appId: '1:488476540503:android:620572f038c879e4076d12',
    messagingSenderId: '488476540503',
    projectId: 'andriod-43852',
    storageBucket: 'andriod-43852.firebasestorage.app',
  );
}
